package interfface.Login_Variant;

import java.awt.Color;
import java.awt.Font;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.register.RegisterDAO;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author angel
 */
public class dialogRegister extends javax.swing.JDialog {
    int xMouse, yMouse;
    ImageIcon emailError = new ImageIcon("src/Images/Register/EmailErrorR.png");
    ImageIcon passError = new ImageIcon("src/Images/Register/PasswordErrorR.png");
    ImageIcon userError = new ImageIcon("src/Images/Register/UserErrorR.png");
    ImageIcon register = new ImageIcon("src/Images/Register/Register.png");
    public dialogRegister(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0,0,0,0));
        JPBG.setBackground(new Color(0,0,0,0));
        jLPEye.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPBG = new javax.swing.JPanel();
        jLPEye = new javax.swing.JLabel();
        jLPEyeClose = new javax.swing.JLabel();
        jBSignUp = new javax.swing.JButton();
        jBLogin = new javax.swing.JButton();
        jTFEmail = new javax.swing.JTextField();
        jTFUser = new javax.swing.JTextField();
        jTPassword = new javax.swing.JPasswordField();
        jLSuccess = new javax.swing.JLabel();
        jLErrorEmail = new javax.swing.JLabel();
        jLBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLPEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/white eye.png"))); // NOI18N
        jLPEye.setPreferredSize(new java.awt.Dimension(15, 15));
        jLPEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLPEyeMouseClicked(evt);
            }
        });
        JPBG.add(jLPEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 345, -1, -1));

        jLPEyeClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/closeeye.png"))); // NOI18N
        jLPEyeClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLPEyeCloseMouseClicked(evt);
            }
        });
        JPBG.add(jLPEyeClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 345, -1, -1));

        jBSignUp.setBackground(new java.awt.Color(33, 33, 33));
        jBSignUp.setBorder(null);
        jBSignUp.setBorderPainted(false);
        jBSignUp.setContentAreaFilled(false);
        jBSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSignUp.setPreferredSize(new java.awt.Dimension(307, 42));
        jBSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBSignUpMouseExited(evt);
            }
        });
        jBSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSignUpActionPerformed(evt);
            }
        });
        JPBG.add(jBSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 403, -1, -1));

        jBLogin.setFont(new java.awt.Font("Lato Black", 1, 13)); // NOI18N
        jBLogin.setForeground(new java.awt.Color(64, 154, 146));
        jBLogin.setText("Already have an account?");
        jBLogin.setBorder(null);
        jBLogin.setContentAreaFilled(false);
        jBLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBLoginMouseExited(evt);
            }
        });
        jBLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLoginActionPerformed(evt);
            }
        });
        JPBG.add(jBLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 445, -1, -1));

        jTFEmail.setBackground(new java.awt.Color(33, 33, 33));
        jTFEmail.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jTFEmail.setForeground(new java.awt.Color(192, 192, 192));
        jTFEmail.setText("E-mail");
        jTFEmail.setBorder(null);
        jTFEmail.setOpaque(true);
        jTFEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFEmailFocusLost(evt);
            }
        });
        jTFEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFEmailKeyTyped(evt);
            }
        });
        JPBG.add(jTFEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 230, 250, 25));

        jTFUser.setBackground(new java.awt.Color(33, 33, 33));
        jTFUser.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jTFUser.setForeground(new java.awt.Color(192, 192, 192));
        jTFUser.setText("Username");
        jTFUser.setBorder(null);
        jTFUser.setOpaque(true);
        jTFUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFUserFocusLost(evt);
            }
        });
        jTFUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFUserKeyTyped(evt);
            }
        });
        JPBG.add(jTFUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 284, 250, 25));

        jTPassword.setBackground(new java.awt.Color(33, 33, 33));
        jTPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTPassword.setForeground(new java.awt.Color(192, 192, 192));
        jTPassword.setText("Password");
        jTPassword.setBorder(null);
        jTPassword.setCaretColor(new java.awt.Color(230, 230, 230));
        jTPassword.setEchoChar((char)0);
        jTPassword.setOpaque(true);
        jTPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTPasswordFocusLost(evt);
            }
        });
        jTPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTPasswordKeyTyped(evt);
            }
        });
        JPBG.add(jTPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 338, 230, 25));

        jLSuccess.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLSuccess.setForeground(new java.awt.Color(0, 211, 128));
        JPBG.add(jLSuccess, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jLErrorEmail.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jLErrorEmail.setForeground(new java.awt.Color(237, 66, 69));
        JPBG.add(jLErrorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 208, -1, -1));

        jLBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Register/Register.png"))); // NOI18N
        JPBG.add(jLBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(JPBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1166, 668));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLPEyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLPEyeMouseClicked
        jLPEyeClose.setVisible(true);
        jLPEyeClose.setEnabled(true);
        jTPassword.setFont(new Font("Lato", Font.BOLD, 14));
        jTPassword.setEchoChar((char)0);
        jLPEye.setVisible(false);
        jLPEye.setEnabled(false);
    }//GEN-LAST:event_jLPEyeMouseClicked

    private void jLPEyeCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLPEyeCloseMouseClicked
        ShowOff();
    }//GEN-LAST:event_jLPEyeCloseMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jTFEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFEmailFocusGained
        jLBG.setIcon(register);
        jLErrorEmail.setText("");
        if (jTFEmail.getText().equals("E-mail") || (jTFEmail.getText().equals(""))) {
            jTFEmail.setText("");
        }
    }//GEN-LAST:event_jTFEmailFocusGained

    private void jTFEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFEmailFocusLost
        if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", jTFEmail.getText()))){
            jLBG.setIcon(emailError);
            jLErrorEmail.setText("Invalid E-mail");
            jTFEmail.setText("E-mail");
        }
    }//GEN-LAST:event_jTFEmailFocusLost

    private void jTFUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFUserFocusGained
        if ((jTFUser.getText().toLowerCase().equals("username") || (jTFUser.getText().toLowerCase().equals("")))) {
            jTFUser.setText("");
        }
    }//GEN-LAST:event_jTFUserFocusGained

    private void jTFUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFUserFocusLost
        if ((jTFUser.getText().toLowerCase().equals("username") || (jTFUser.getText().toLowerCase().equals("")))) {
            jLBG.setIcon(userError);
            jTFUser.setText("Username");
        }
    }//GEN-LAST:event_jTFUserFocusLost

    private void jTPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTPasswordFocusGained
        ShowOff();
        jLErrorEmail.setText("");
        String pass = String.valueOf(jTPassword.getPassword());
        if (((pass.toLowerCase().equals("password")) || (pass.toLowerCase().equals("")))) {
            jTPassword.setText("");
        }
    }//GEN-LAST:event_jTPasswordFocusGained

    private void jTPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTPasswordFocusLost
        String pass = String.valueOf(jTPassword.getPassword());
        if (((pass.toLowerCase().equals("password")) || (pass.toLowerCase().equals("")))) {
            jLBG.setIcon(passError);
            jTPassword.setText("Password");
            jTPassword.setEchoChar((char)0);
        }
    }//GEN-LAST:event_jTPasswordFocusLost

    private void jBLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginActionPerformed
        this.dispose();
        new dialogLogin(null, true).setVisible(true);
    }//GEN-LAST:event_jBLoginActionPerformed

    private void jBLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLoginMouseEntered
        jBLogin.setText("<HTML><U>Already have an account?</UL></HTML>");
    }//GEN-LAST:event_jBLoginMouseEntered

    private void jBLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLoginMouseExited
        jBLogin.setText("Already have an account?");
    }//GEN-LAST:event_jBLoginMouseExited
    
    private void jBSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSignUpActionPerformed
        String email = jTFEmail.getText().toLowerCase();
        String user = jTFUser.getText();
        String pass = String.valueOf(jTPassword.getPassword()); 
        
        if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", email))){
            jLBG.setIcon(emailError);
            jLErrorEmail.setText("Invalid E-mail");
            return;
        }

        if ((user.trim().isEmpty()) || (user.toLowerCase().equals("username"))) {
            jLBG.setIcon(userError);
            jTFUser.setText("Username");
            return;
        }

        if (((pass.toLowerCase().equals("password")) || (pass.toLowerCase().equals("")))) {
            jLBG.setIcon(passError);
            jTPassword.setText("Password");
            jTPassword.setEchoChar((char)0);
            return;
        }
        
        try {
            ResultSet rs = RegisterDAO.emailExists(email);
            if (rs.next()) {
              jLBG.setIcon(emailError);  
              jLErrorEmail.setText("E-mail Already Exists");
              return;
            }
        } catch (SQLException ex) {
            Logger.getLogger(dialogRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            PreparedStatement ps = RegisterDAO.register(email, user, pass);
            if(ps.executeUpdate() > 0){
                jLSuccess.setText("Successfully Registered");  
                jTFUser.setText("Username");
                jTFEmail.setText("E-mail");
                jTPassword.setText("Password");
                jTPassword.setEchoChar((char)0);
            }
        } catch (SQLException ex) {
            Logger.getLogger(dialogRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBSignUpActionPerformed

    private void jBSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSignUpMouseExited
        jBSignUp.setIcon(null);
    }//GEN-LAST:event_jBSignUpMouseExited

    private void jBSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSignUpMouseEntered
        jBSignUp.setIcon(new ImageIcon("Src/Images/Register/SignUpPressed.png"));
    }//GEN-LAST:event_jBSignUpMouseEntered

    private void jTFUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFUserKeyTyped
        if (jTFUser.getText().toLowerCase().equals("")) {
            jLBG.setIcon(register);    
        }
    }//GEN-LAST:event_jTFUserKeyTyped

    private void jTPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTPasswordKeyTyped
        String pass = String.valueOf(jTPassword.getPassword());
        if (pass.toLowerCase().equals("")) {
            jLBG.setIcon(register);    
        }
    }//GEN-LAST:event_jTPasswordKeyTyped

    private void jTFEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFEmailKeyTyped
        if (jTFEmail.getText().toLowerCase().equals("")) {
            jLBG.setIcon(register);    
        }
    }//GEN-LAST:event_jTFEmailKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialogRegister dialog = new dialogRegister(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void ShowOff(){
        jLPEye.setVisible(true);
        jLPEye.setEnabled(true);
        jTPassword.setFont(new Font("Tahoma", Font.BOLD, 12));
        jTPassword.setEchoChar('\u25cf');
        jLPEyeClose.setVisible(false);
        jLPEyeClose.setEnabled(false);
    }
    
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPBG;
    private javax.swing.JButton jBLogin;
    private javax.swing.JButton jBSignUp;
    private javax.swing.JLabel jLBG;
    private javax.swing.JLabel jLErrorEmail;
    private javax.swing.JLabel jLPEye;
    private javax.swing.JLabel jLPEyeClose;
    private javax.swing.JLabel jLSuccess;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFUser;
    private javax.swing.JPasswordField jTPassword;
    // End of variables declaration//GEN-END:variables
}
