/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfface.Login_Variant;

import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import java.awt.Color;
import javax.swing.JTextField;

/**
 *
 * @author angel
 */
public class dialogDashBoard extends javax.swing.JDialog {
    int xMouse, yMouse;
    Color o100 = new Color(0,0,0,0);
    /**
     * Creates new form dialogDashBoard
     */
    public dialogDashBoard(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setBackground(o100);
        jPBG.setBackground(o100);
        jTFBreakFast.setHorizontalAlignment(JTextField.CENTER);
        jTFLunch.setHorizontalAlignment(JTextField.CENTER);
        jTFSnack1.setHorizontalAlignment(JTextField.CENTER);
        jTFSnack2.setHorizontalAlignment(JTextField.CENTER);
        jTFDinner.setHorizontalAlignment(JTextField.CENTER);
        jTFMidnight.setHorizontalAlignment(JTextField.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBG = new javax.swing.JPanel();
        jTFBreakFast = new javax.swing.JTextField();
        jTFLunch = new javax.swing.JTextField();
        jTFSnack1 = new javax.swing.JTextField();
        jTFSnack2 = new javax.swing.JTextField();
        jTFDinner = new javax.swing.JTextField();
        jTFMidnight = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFBreakFast.setBackground(o100);
        jTFBreakFast.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jTFBreakFast.setForeground(new java.awt.Color(255, 255, 255));
        jTFBreakFast.setText("Breakfast");
        jTFBreakFast.setToolTipText(null);
        jTFBreakFast.setBorder(null);
        jTFBreakFast.setCaretColor(new java.awt.Color(255, 255, 255));
        jTFBreakFast.setVerifyInputWhenFocusTarget(false);
        jTFBreakFast.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFBreakFastFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFBreakFastFocusLost(evt);
            }
        });
        jPBG.add(jTFBreakFast, new org.netbeans.lib.awtextra.AbsoluteConstraints(977, 327, 240, 25));

        jTFLunch.setBackground(o100);
        jTFLunch.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jTFLunch.setForeground(new java.awt.Color(255, 255, 255));
        jTFLunch.setText("Lunch");
        jTFLunch.setToolTipText(null);
        jTFLunch.setBorder(null);
        jTFLunch.setCaretColor(new java.awt.Color(255, 255, 255));
        jTFLunch.setVerifyInputWhenFocusTarget(false);
        jTFLunch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFLunchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFLunchFocusLost(evt);
            }
        });
        jPBG.add(jTFLunch, new org.netbeans.lib.awtextra.AbsoluteConstraints(977, 371, 240, 25));

        jTFSnack1.setBackground(o100);
        jTFSnack1.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jTFSnack1.setForeground(new java.awt.Color(255, 255, 255));
        jTFSnack1.setText("1st Snack");
        jTFSnack1.setToolTipText(null);
        jTFSnack1.setBorder(null);
        jTFSnack1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTFSnack1.setVerifyInputWhenFocusTarget(false);
        jTFSnack1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFSnack1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFSnack1FocusLost(evt);
            }
        });
        jPBG.add(jTFSnack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(977, 416, 240, 25));

        jTFSnack2.setBackground(o100);
        jTFSnack2.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jTFSnack2.setForeground(new java.awt.Color(255, 255, 255));
        jTFSnack2.setText("2nd Snack");
        jTFSnack2.setToolTipText(null);
        jTFSnack2.setBorder(null);
        jTFSnack2.setCaretColor(new java.awt.Color(255, 255, 255));
        jTFSnack2.setVerifyInputWhenFocusTarget(false);
        jTFSnack2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFSnack2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFSnack2FocusLost(evt);
            }
        });
        jPBG.add(jTFSnack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(977, 461, 240, 25));

        jTFDinner.setBackground(o100);
        jTFDinner.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jTFDinner.setForeground(new java.awt.Color(255, 255, 255));
        jTFDinner.setText("Dinner");
        jTFDinner.setToolTipText(null);
        jTFDinner.setBorder(null);
        jTFDinner.setCaretColor(new java.awt.Color(255, 255, 255));
        jTFDinner.setVerifyInputWhenFocusTarget(false);
        jTFDinner.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFDinnerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFDinnerFocusLost(evt);
            }
        });
        jPBG.add(jTFDinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(977, 506, 240, 25));

        jTFMidnight.setBackground(o100);
        jTFMidnight.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jTFMidnight.setForeground(new java.awt.Color(255, 255, 255));
        jTFMidnight.setText("Midnight");
        jTFMidnight.setToolTipText(null);
        jTFMidnight.setBorder(null);
        jTFMidnight.setCaretColor(new java.awt.Color(255, 255, 255));
        jTFMidnight.setVerifyInputWhenFocusTarget(false);
        jTFMidnight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFMidnightFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFMidnightFocusLost(evt);
            }
        });
        jPBG.add(jTFMidnight, new org.netbeans.lib.awtextra.AbsoluteConstraints(977, 550, 240, 25));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPBG.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 297, 559, 311));

        jLBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dash/DashBoard.png"))); // NOI18N
        jPBG.add(jLBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();;
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void jTFBreakFastFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFBreakFastFocusGained
        if ((jTFBreakFast.getText().equals("Breakfast") || (jTFBreakFast.getText().equals("")))) {
            jTFBreakFast.setText("");
            return;
        }        
    }//GEN-LAST:event_jTFBreakFastFocusGained

    private void jTFBreakFastFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFBreakFastFocusLost
        if ((jTFBreakFast.getText().equals("E-mail") || (jTFBreakFast.getText().equals("")))) {
            jTFBreakFast.setText("Breakfast");  
        }
    }//GEN-LAST:event_jTFBreakFastFocusLost

    private void jTFLunchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFLunchFocusGained
        if ((jTFLunch.getText().equals("Lunch") || (jTFLunch.getText().equals("")))) {
            jTFLunch.setText("");
            return;
        }       
    }//GEN-LAST:event_jTFLunchFocusGained

    private void jTFLunchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFLunchFocusLost
        if ((jTFLunch.getText().equals("Lunch") || (jTFLunch.getText().equals("")))) {
            jTFLunch.setText("Lunch");  
        }
    }//GEN-LAST:event_jTFLunchFocusLost

    private void jTFSnack1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFSnack1FocusGained
        if ((jTFSnack1.getText().equals("1st Snack") || (jTFSnack1.getText().equals("")))) {
            jTFSnack1.setText("");
            return;
        }   
    }//GEN-LAST:event_jTFSnack1FocusGained

    private void jTFSnack1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFSnack1FocusLost
        if ((jTFSnack1.getText().equals("1st Snack") || (jTFSnack1.getText().equals("")))) {
            jTFSnack1.setText("1st Snack");  
        }
    }//GEN-LAST:event_jTFSnack1FocusLost

    private void jTFSnack2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFSnack2FocusGained
        if ((jTFSnack2.getText().equals("2nd Snack") || (jTFSnack2.getText().equals("")))) {
            jTFSnack2.setText("");
            return;
        }   
    }//GEN-LAST:event_jTFSnack2FocusGained

    private void jTFSnack2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFSnack2FocusLost
        if ((jTFSnack2.getText().equals("2nd Snack") || (jTFSnack2.getText().equals("")))) {
            jTFSnack2.setText("2nd Snack");  
        }
    }//GEN-LAST:event_jTFSnack2FocusLost

    private void jTFDinnerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFDinnerFocusGained
        if ((jTFDinner.getText().equals("Dinner") || (jTFDinner.getText().equals("")))) {
            jTFDinner.setText("");
            return;
        }   
    }//GEN-LAST:event_jTFDinnerFocusGained

    private void jTFDinnerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFDinnerFocusLost
        if ((jTFDinner.getText().equals("Dinner") || (jTFDinner.getText().equals("")))) {
            jTFDinner.setText("Dinner");  
        }
    }//GEN-LAST:event_jTFDinnerFocusLost

    private void jTFMidnightFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFMidnightFocusGained
        if ((jTFMidnight.getText().equals("Midnight") || (jTFMidnight.getText().equals("")))) {
            jTFMidnight.setText("");
            return;
        }   
    }//GEN-LAST:event_jTFMidnightFocusGained

    private void jTFMidnightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFMidnightFocusLost
        if ((jTFMidnight.getText().equals("Midnight") || (jTFMidnight.getText().equals("")))) {
            jTFMidnight.setText("Midnight");  
        }
    }//GEN-LAST:event_jTFMidnightFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatCyanLightIJTheme.setup();
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialogDashBoard dialog = new dialogDashBoard(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLBG;
    private javax.swing.JPanel jPBG;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFBreakFast;
    private javax.swing.JTextField jTFDinner;
    private javax.swing.JTextField jTFLunch;
    private javax.swing.JTextField jTFMidnight;
    private javax.swing.JTextField jTFSnack1;
    private javax.swing.JTextField jTFSnack2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
