package interfface;

import java.awt.Color;
import java.awt.Font;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author angel
 */
public class dialogRegister extends javax.swing.JDialog {
    int xMouse, yMouse;
    /**
     * Creates new form dialogRegister
     */
    public dialogRegister(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0,0,0,0));
        JPBG.setBackground(new Color(0,0,0,0));
        jLPEye.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPBG = new javax.swing.JPanel();
        jTFEmail = new javax.swing.JTextField();
        JTPassword = new javax.swing.JPasswordField();
        jLPEye = new javax.swing.JLabel();
        jLPEyeClose = new javax.swing.JLabel();
        jBSignUp = new javax.swing.JButton();
        jTFUser = new javax.swing.JTextField();
        jLLogin = new javax.swing.JLabel();
        jLBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFEmail.setBackground(new java.awt.Color(33, 33, 33));
        jTFEmail.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jTFEmail.setForeground(new java.awt.Color(192, 192, 192));
        jTFEmail.setText("E-mail");
        jTFEmail.setToolTipText(null);
        jTFEmail.setBorder(null);
        jTFEmail.setOpaque(true);
        jTFEmail.setVerifyInputWhenFocusTarget(false);
        jTFEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFEmailFocusLost(evt);
            }
        });
        JPBG.add(jTFEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 240, 25));

        JTPassword.setBackground(new java.awt.Color(33, 33, 33));
        JTPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JTPassword.setForeground(new java.awt.Color(192, 192, 192));
        JTPassword.setText("Password");
        JTPassword.setBorder(null);
        JTPassword.setCaretColor(new java.awt.Color(230, 230, 230));
        JTPassword.setEchoChar((char)0);
        JTPassword.setFocusAccelerator('8');
        JTPassword.setOpaque(true);
        JTPassword.setPreferredSize(new java.awt.Dimension(224, 25));
        JTPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTPasswordFocusLost(evt);
            }
        });
        JPBG.add(JTPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 338, -1, -1));

        jLPEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/white eye.png"))); // NOI18N
        jLPEye.setPreferredSize(new java.awt.Dimension(15, 15));
        jLPEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLPEyeMouseClicked(evt);
            }
        });
        JPBG.add(jLPEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 345, -1, -1));

        jLPEyeClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/closeeye.png"))); // NOI18N
        jLPEyeClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLPEyeCloseMouseClicked(evt);
            }
        });
        JPBG.add(jLPEyeClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 345, -1, -1));

        jBSignUp.setBackground(new java.awt.Color(33, 33, 33));
        jBSignUp.setBorder(null);
        jBSignUp.setBorderPainted(false);
        jBSignUp.setContentAreaFilled(false);
        jBSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSignUp.setPreferredSize(new java.awt.Dimension(307, 42));
        jBSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBSignUpMouseExited(evt);
            }
        });
        JPBG.add(jBSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 403, -1, -1));

        jTFUser.setBackground(new java.awt.Color(33, 33, 33));
        jTFUser.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jTFUser.setForeground(new java.awt.Color(192, 192, 192));
        jTFUser.setText("Username");
        jTFUser.setToolTipText(null);
        jTFUser.setBorder(null);
        jTFUser.setOpaque(true);
        jTFUser.setVerifyInputWhenFocusTarget(false);
        JPBG.add(jTFUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 284, 240, 25));

        jLLogin.setFont(new java.awt.Font("Lato Black", 1, 13)); // NOI18N
        jLLogin.setForeground(new java.awt.Color(64, 154, 146));
        jLLogin.setText("Already have an account?");
        jLLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLLoginMouseExited(evt);
            }
        });
        JPBG.add(jLLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 445, -1, -1));

        jLBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Register/Register.png"))); // NOI18N
        JPBG.add(jLBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(JPBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1166, 668));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFEmailFocusGained
        jLBG.setIcon(new ImageIcon("src/Images/Register/Register.png"));
//        jLErrorMail.setText("");
        if ((jTFEmail.getText().equals("E-mail"))) {
            jTFEmail.setText("");
        }
    }//GEN-LAST:event_jTFEmailFocusGained

    private void jTFEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFEmailFocusLost
        if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", jTFEmail.getText()))){
            jLBG.setIcon(new ImageIcon("src/Images/Register/EmailErrorR.png"));
//            jLErrorMail.setText("Invalid E-mail");
            jTFEmail.setText("E-mail");
        }
    }//GEN-LAST:event_jTFEmailFocusLost

    private void jLPEyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLPEyeMouseClicked
        jLPEyeClose.setVisible(true);
        jLPEyeClose.setEnabled(true);
        JTPassword.setFont(new Font("Lato", Font.BOLD, 14));
        JTPassword.setEchoChar((char)0);
        jLPEye.setVisible(false);
        jLPEye.setEnabled(false);
    }//GEN-LAST:event_jLPEyeMouseClicked

    private void jLPEyeCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLPEyeCloseMouseClicked
        ShowOff();
    }//GEN-LAST:event_jLPEyeCloseMouseClicked

    private void JTPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTPasswordFocusGained
        ShowOff();
        jLBG.setIcon(new ImageIcon("src/Images/Register/Register.png"));
        String pass = String.valueOf(JTPassword.getPassword());
        if (pass.toLowerCase().equals("password")) {
            JTPassword.setText("");            
        }
        
    }//GEN-LAST:event_JTPasswordFocusGained

    private void JTPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTPasswordFocusLost
        String pass = String.valueOf(JTPassword.getPassword());
        if (((pass.toLowerCase().equals("password")) || (pass.toLowerCase().equals("")))) {
            jLBG.setIcon(new ImageIcon("src/Images/Register/PasswordErrorR.png"));
            JTPassword.setText("Password");
            JTPassword.setEchoChar((char)0);
        }
    }//GEN-LAST:event_JTPasswordFocusLost

    private void jBSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSignUpMouseEntered
        jBSignUp.setIcon(new ImageIcon("Src/Images/Register/SignUpPressed.png"));
    }//GEN-LAST:event_jBSignUpMouseEntered

    private void jBSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSignUpMouseExited
        jBSignUp.setIcon(null);
    }//GEN-LAST:event_jBSignUpMouseExited

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jLLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLoginMouseEntered
        jLLogin.setText("<HTML><U>Already have an account?</UL></HTML>");
    }//GEN-LAST:event_jLLoginMouseEntered

    private void jLLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLoginMouseExited
        jLLogin.setText("Already have an account?");
    }//GEN-LAST:event_jLLoginMouseExited

    private void jLLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLoginMouseClicked
        dispose();
        new dialogLogin(null, true).setVisible(true);
    }//GEN-LAST:event_jLLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialogRegister dialog = new dialogRegister(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void ShowOff(){
        jLPEye.setVisible(true);
        jLPEye.setEnabled(true);
        JTPassword.setFont(new Font("Tahoma", Font.BOLD, 12));
        JTPassword.setEchoChar('\u25cf');
        jLPEyeClose.setVisible(false);
        jLPEyeClose.setEnabled(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPBG;
    private javax.swing.JPasswordField JTPassword;
    private javax.swing.JButton jBSignUp;
    private javax.swing.JLabel jLBG;
    private javax.swing.JLabel jLLogin;
    private javax.swing.JLabel jLPEye;
    private javax.swing.JLabel jLPEyeClose;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFUser;
    // End of variables declaration//GEN-END:variables
}
